### ISSUE TITLE
Iteration Not Working

### ISSUE THREAD

**Issue by queejie** [greim/html-tokenizer#3]
Thanks for this module.  It is just what I need for text highlighting, I think.  Unfortunately, I can't get it to iterate.  My code is nearly identical to the code in the docs.  I never see any console messages (unless I put one in prior to the for loop):

![image](https://user-images.githubusercontent.com/1616827/56159315-5a846200-5f92-11e9-984c-2c8f3c28c148.png)

Any ideas on what I might be missing or doing incorrectly?

**Comment by greim** [comment]
Sorry, just saw this. Hard to tell what's wrong from the given code sample; it looks like it should work. Perhaps try cloning the repo and seeing if the unit tests run on your machine. If those fail, let me know your OS, JS engine version, etc. Otherwise, next step, try adding a unit test which captures your particular error scenario.

**Comment by queejie** [comment]
Thanks, I resolved this by using:
`import  {Tokenizer} from 'html-tokenizer';`
rather than the require().
